### ISSUE TITLE
I'm sorry I'm Stupid. How do I build a driver

### ISSUE THREAD

**Issue by goldenfett** [devmapal/nvidia-shield-controller-driver#4]
I know a little about computer science but where should I start? And does this work for windows 10? Thanks and sorry for the dumb question

**Comment by devmapal** [comment]
Sry, linux only at the moment. You will need to apply the patches to linux kernel sources and then build it. There is great documentation out there on how to build a custom linux kernel.

Feel free to reopen the issue if you have any further questions
